package baobab.notebookfx.utils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class CheckFile {

    private static final String IMAGE_EXTENSIONS = "(^[\\s\\S]+(\\.(?i)(jpg|jpeg|png|gif|svg))$)";
    private static final Pattern PATTERN_EXTENSIONS = Pattern.compile(IMAGE_EXTENSIONS);

    public static boolean isFileImage(File image) {
        return PATTERN_EXTENSIONS.matcher(image.getName()).matches();
    }

    private static final String IMAGE_IDENTIFIER = "@\\[(.+?)\\]\\(\\)";
    private static final Pattern PATTERN_IDENTIFIER = Pattern.compile(IMAGE_IDENTIFIER);

    public static String getImageIdentifier(String content) {
        Matcher matcher = PATTERN_IDENTIFIER.matcher(content);
        if (matcher.find()) {
            return matcher.group(1);
        }
        return null;
    }

    public static String isTextFile(File f) {
        String languageMode = "";
        try {
            String mimeType = Files.probeContentType(f.toPath());
            String fileName = f.getName();
            int index = fileName.lastIndexOf('.');
            String extension = index > 0 ? fileName.substring(index) : "";

            // Check by MimeType
            Optional<P> mode = P.getProgramLang().stream()
                    .filter(p -> p.getMimeType() != null)
                    .filter(p -> p.getMimeType().equals(mimeType))
                    .findFirst();
            if (mode.isPresent()) {
                languageMode = mode.get().getLanguageMode();
            }
            // Check by extension
            if (languageMode.isEmpty() && !extension.isEmpty()) {
                Optional<P> m = P.getProgramLang().stream()
                        .filter(p -> p.getExtensions() != null)
                        .filter(p -> Arrays.asList(p.getExtensions()).contains(extension))
                        .findFirst();
                if (m.isPresent()) {
                    languageMode = m.get().getLanguageMode();
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(CheckFile.class.getName()).log(Level.SEVERE, null, ex);
        }
        return languageMode;
    }

    public static final class P {

        private String languageName;
        private String languageMode;
        private String mimeType;
        private String[] extensions;

        private P(String languageName, String languageMode, String mimeType, String... extensions) {
            this.languageName = languageName;
            this.languageMode = languageMode;
            this.mimeType = mimeType;
            this.extensions = extensions;
        }

        public String getMimeType() {
            return mimeType;
        }

        public String[] getExtensions() {
            return extensions;
        }

        public String getLanguageMode() {
            return languageMode;
        }

        /**
         * list generated resource/languages.html
         */
        public static final List<P> getProgramLang() {
            return Arrays.asList(
                    new P("Text", "text", "text/plain", null),
                    new P("1C Enterprise", "text", null, ".bsl", ".os"),
                    new P("ABAP", "abap", null, ".abap"),
                    new P("AGS Script", "c_cpp", "text/x-c++src", ".asc", ".ash"),
                    new P("AMPL", "text", null, ".ampl", ".mod"),
                    new P("ANTLR", "text", null, ".g4"),
                    new P("API Blueprint", "markdown", null, ".apib"),
                    new P("APL", "text", "text/apl", ".apl", ".dyalog"),
                    new P("ASN.1", "text", "text/x-ttcn-asn", ".asn", ".asn1"),
                    new P("ASP", "text", "application/x-aspx", ".asp", ".asax", ".ascx", ".ashx", ".asmx", ".aspx", ".axd"),
                    new P("ATS", "ocaml", null, ".dats", ".hats", ".sats"),
                    new P("ActionScript", "actionscript", null, ".as"),
                    new P("Ada", "ada", null, ".adb", ".ada", ".ads"),
                    new P("Adobe Font Metrics", "text", null, ".afm"),
                    new P("Agda", "text", null, ".agda"),
                    new P("Alloy", "text", null, ".als"),
                    new P("Alpine Abuild", "sh", "text/x-sh", null),
                    new P("AngelScript", "text", "text/x-c++src", ".as", ".angelscript"),
                    new P("Ant Build System", "xml", "application/xml", null),
                    new P("ApacheConf", "apache_conf", null, ".apacheconf", ".vhost"),
                    new P("Apex", "java", "text/x-java", ".cls"),
                    new P("Apollo Guidance Computer", "assembly_x86", null, ".agc"),
                    new P("AppleScript", "applescript", null, ".applescript", ".scpt"),
                    new P("Arc", "text", null, ".arc"),
                    new P("AsciiDoc", "asciidoc", null, ".asciidoc", ".adoc", ".asc"),
                    new P("AspectJ", "text", null, ".aj"),
                    new P("Assembly", "assembly_x86", null, ".asm", ".a51", ".inc", ".nasm"),
                    new P("Augeas", "text", null, ".aug"),
                    new P("AutoHotkey", "autohotkey", null, ".ahk", ".ahkl"),
                    new P("AutoIt", "autohotkey", null, ".au3"),
                    new P("Awk", "text", null, ".awk", ".auk", ".gawk", ".mawk", ".nawk"),
                    new P("Ballerina", "text", null, ".bal"),
                    new P("Batchfile", "batchfile", null, ".bat", ".cmd"),
                    new P("Befunge", "text", null, ".befunge"),
                    new P("Bison", "text", null, ".bison"),
                    new P("BitBake", "text", null, ".bb"),
                    new P("Blade", "text", null, ".blade", ".blade.php"),
                    new P("BlitzBasic", "text", null, ".bb", ".decls"),
                    new P("BlitzMax", "text", null, ".bmx"),
                    new P("Bluespec", "verilog", null, ".bsv"),
                    new P("Boo", "text", null, ".boo"),
                    new P("Brainfuck", "text", "text/x-brainfuck", ".b", ".bf"),
                    new P("Brightscript", "text", null, ".brs"),
                    new P("Bro", "text", null, ".bro"),
                    new P("C", "c_cpp", "text/x-csrc", ".c", ".cats", ".h", ".idc"),
                    new P("C#", "csharp", "text/x-csharp", ".cs", ".cake", ".cshtml", ".csx"),
                    new P("C++", "c_cpp", "text/x-c++src", ".cpp", ".c++", ".cc", ".cp", ".cxx", ".h", ".h++", ".hh", ".hpp", ".hxx", ".inc", ".inl", ".ino", ".ipp", ".re", ".tcc", ".tpp"),
                    new P("C-ObjDump", "assembly_x86", null, ".c-objdump"),
                    new P("C2hs Haskell", "haskell", "text/x-haskell", ".chs"),
                    new P("CLIPS", "text", null, ".clp"),
                    new P("CMake", "text", "text/x-cmake", ".cmake", ".cmake.in"),
                    new P("COBOL", "cobol", "text/x-cobol", ".cob", ".cbl", ".ccp", ".cobol", ".cpy"),
                    new P("COLLADA", "xml", "text/xml", ".dae"),
                    new P("CSON", "coffee", "text/x-coffeescript", ".cson"),
                    new P("CSS", "css", "text/css", ".css"),
                    new P("CSV", "text", null, ".csv"),
                    new P("CWeb", "text", null, ".w"),
                    new P("Cap'n Proto", "text", null, ".capnp"),
                    new P("CartoCSS", "text", null, ".mss"),
                    new P("Ceylon", "text", null, ".ceylon"),
                    new P("Chapel", "text", null, ".chpl"),
                    new P("Charity", "text", null, ".ch"),
                    new P("ChucK", "java", "text/x-java", ".ck"),
                    new P("Cirru", "cirru", null, ".cirru"),
                    new P("Clarion", "text", null, ".clw"),
                    new P("Clean", "text", null, ".icl", ".dcl"),
                    new P("Click", "text", null, ".click"),
                    new P("Clojure", "clojure", "text/x-clojure", ".clj", ".boot", ".cl2", ".cljc", ".cljs", ".cljs.hl", ".cljscm", ".cljx", ".hic"),
                    new P("Closure Templates", "soy_template", "text/x-soy", ".soy"),
                    new P("CoNLL-U", "text", null, ".conllu", ".conll"),
                    new P("CoffeeScript", "coffee", "text/x-coffeescript", ".coffee", "._coffee", ".cake", ".cjsx", ".iced"),
                    new P("ColdFusion", "coldfusion", null, ".cfm", ".cfml"),
                    new P("ColdFusion CFC", "coldfusion", null, ".cfc"),
                    new P("Common Lisp", "lisp", "text/x-common-lisp", ".lisp", ".asd", ".cl", ".l", ".lsp", ".ny", ".podsl", ".sexp"),
                    new P("Common Workflow Language", "yaml", "text/x-yaml", ".cwl"),
                    new P("Component Pascal", "pascal", "text/x-pascal", ".cp", ".cps"),
                    new P("Cool", "text", null, ".cl"),
                    new P("Coq", "text", null, ".coq", ".v"),
                    new P("Cpp-ObjDump", "assembly_x86", null, ".cppobjdump", ".c++-objdump", ".c++objdump", ".cpp-objdump", ".cxx-objdump"),
                    new P("Creole", "text", null, ".creole"),
                    new P("Crystal", "ruby", "text/x-crystal", ".cr"),
                    new P("Csound", "csound_orchestra", null, ".orc", ".udo"),
                    new P("Csound Document", "csound_document", null, ".csd"),
                    new P("Csound Score", "csound_score", null, ".sco"),
                    new P("Cuda", "c_cpp", "text/x-c++src", ".cu", ".cuh"),
                    new P("Cycript", "javascript", "text/javascript", ".cy"),
                    new P("Cython", "text", "text/x-cython", ".pyx", ".pxd", ".pxi"),
                    new P("D", "d", "text/x-d", ".d", ".di"),
                    new P("D-ObjDump", "assembly_x86", null, ".d-objdump"),
                    new P("DIGITAL Command Language", "text", null, ".com"),
                    new P("DM", "c_cpp", null, ".dm"),
                    new P("DNS Zone", "text", null, ".zone", ".arpa"),
                    new P("DTrace", "c_cpp", "text/x-csrc", ".d"),
                    new P("Darcs Patch", "text", null, ".darcspatch", ".dpatch"),
                    new P("Dart", "dart", "application/dart", ".dart"),
                    new P("DataWeave", "text", null, ".dwl"),
                    new P("Diff", "diff", "text/x-diff", ".diff", ".patch"),
                    new P("Dockerfile", "dockerfile", "text/x-dockerfile", ".dockerfile"),
                    new P("Dogescript", "text", null, ".djs"),
                    new P("Dylan", "text", "text/x-dylan", ".dylan", ".dyl", ".intr", ".lid"),
                    new P("E", "text", null, ".E"),
                    new P("EBNF", "text", "text/x-ebnf", ".ebnf"),
                    new P("ECL", "text", "text/x-ecl", ".ecl", ".eclxml"),
                    new P("ECLiPSe", "prolog", null, ".ecl"),
                    new P("EJS", "ejs", null, ".ejs"),
                    new P("EQ", "csharp", "text/x-csharp", ".eq"),
                    new P("Eagle", "xml", "text/xml", ".sch", ".brd"),
                    new P("Easybuild", "python", "text/x-python", ".eb"),
                    new P("Ecere Projects", "json", "application/json", ".epj"),
                    new P("Edje Data Collection", "json", "application/json", ".edc"),
                    new P("Eiffel", "eiffel", "text/x-eiffel", ".e"),
                    new P("Elixir", "elixir", null, ".ex", ".exs"),
                    new P("Elm", "elm", "text/x-elm", ".elm"),
                    new P("Emacs Lisp", "lisp", "text/x-common-lisp", ".el", ".emacs", ".emacs.desktop"),
                    new P("EmberScript", "coffee", "text/x-coffeescript", ".em", ".emberscript"),
                    new P("Erlang", "erlang", "text/x-erlang", ".erl", ".app.src", ".es", ".escript", ".hrl", ".xrl", ".yrl"),
                    new P("F#", "text", "text/x-fsharp", ".fs", ".fsi", ".fsx"),
                    new P("FLUX", "text", null, ".fx", ".flux"),
                    new P("Factor", "text", "text/x-factor", ".factor"),
                    new P("Fancy", "text", null, ".fy", ".fancypack"),
                    new P("Fantom", "text", null, ".fan"),
                    new P("Filebench WML", "text", null, ".f"),
                    new P("Filterscript", "text", null, ".fs"),
                    new P("Formatted", "text", null, ".for", ".eam.fs"),
                    new P("Forth", "forth", "text/x-forth", ".fth", ".4th", ".f", ".for", ".forth", ".fr", ".frt", ".fs"),
                    new P("Fortran", "text", "text/x-fortran", ".f90", ".f", ".f03", ".f08", ".f77", ".f95", ".for", ".fpp"),
                    new P("FreeMarker", "ftl", null, ".ftl"),
                    new P("Frege", "haskell", null, ".fr"),
                    new P("G-code", "gcode", null, ".g", ".gco", ".gcode"),
                    new P("GAMS", "text", null, ".gms"),
                    new P("GAP", "text", null, ".g", ".gap", ".gd", ".gi", ".tst"),
                    new P("GCC Machine Description", "lisp", "text/x-common-lisp", ".md"),
                    new P("GDB", "text", null, ".gdb", ".gdbinit"),
                    new P("GDScript", "text", null, ".gd"),
                    new P("GLSL", "glsl", null, ".glsl", ".fp", ".frag", ".frg", ".fs", ".fsh", ".fshader", ".geo", ".geom", ".glslv", ".gshader", ".shader", ".tesc", ".tese", ".vert", ".vrx", ".vsh", ".vshader"),
                    new P("GN", "python", "text/x-python", ".gn", ".gni"),
                    new P("Game Maker Language", "c_cpp", "text/x-c++src", ".gml"),
                    new P("Genie", "text", null, ".gs"),
                    new P("Genshi", "xml", "text/xml", ".kid"),
                    new P("Gentoo Ebuild", "sh", "text/x-sh", ".ebuild"),
                    new P("Gentoo Eclass", "sh", "text/x-sh", ".eclass"),
                    new P("Gerber Image", "text", null, ".gbr", ".gbl", ".gbo", ".gbp", ".gbs", ".gko", ".gpb", ".gpt", ".gtl", ".gto", ".gtp", ".gts"),
                    new P("Gettext Catalog", "text", null, ".po", ".pot"),
                    new P("Gherkin", "text", null, ".feature"),
                    new P("Glyph", "tcl", "text/x-tcl", ".glf"),
                    new P("Gnuplot", "text", null, ".gp", ".gnu", ".gnuplot", ".plot", ".plt"),
                    new P("Go", "golang", "text/x-go", ".go"),
                    new P("Golo", "text", null, ".golo"),
                    new P("Gosu", "text", null, ".gs", ".gst", ".gsx", ".vark"),
                    new P("Grace", "text", null, ".grace"),
                    new P("Gradle", "text", null, ".gradle"),
                    new P("Grammatical Framework", "haskell", "text/x-haskell", ".gf"),
                    new P("Graph Modeling Language", "text", null, ".gml"),
                    new P("GraphQL", "text", null, ".graphql", ".gql"),
                    new P("Graphviz (DOT)", "text", null, ".dot", ".gv"),
                    new P("Groovy", "groovy", "text/x-groovy", ".groovy", ".grt", ".gtpl", ".gvy"),
                    new P("Groovy Server Pages", "jsp", "application/x-jsp", ".gsp"),
                    new P("HCL", "ruby", "text/x-ruby", ".hcl", ".tf", ".tfvars"),
                    new P("HLSL", "text", null, ".hlsl", ".cginc", ".fx", ".fxh", ".hlsli"),
                    new P("HTML", "html", "text/html", ".html", ".htm", ".html.hl", ".inc", ".st", ".xht", ".xhtml"),
                    new P("HTML+Django", "django", "text/x-django", ".jinja", ".jinja2", ".mustache", ".njk"),
                    new P("HTML+ECR", "text", "text/html", ".ecr"),
                    new P("HTML+EEX", "text", "text/html", ".eex"),
                    new P("HTML+ERB", "text", "application/x-erb", ".erb", ".erb.deface"),
                    new P("HTML+PHP", "php", "application/x-httpd-php", ".phtml"),
                    new P("HTTP", "text", "message/http", ".http"),
                    new P("Hack", "php", "application/x-httpd-php", ".hh", ".php"),
                    new P("Haml", "haml", "text/x-haml", ".haml", ".haml.deface"),
                    new P("Handlebars", "handlebars", null, ".handlebars", ".hbs"),
                    new P("Harbour", "text", null, ".hb"),
                    new P("Haskell", "haskell", "text/x-haskell", ".hs", ".hsc"),
                    new P("Haxe", "haxe", "text/x-haxe", ".hx", ".hxsl"),
                    new P("Hy", "text", null, ".hy"),
                    new P("HyPhy", "text", null, ".bf"),
                    new P("IDL", "text", "text/x-idl", ".pro", ".dlm"),
                    new P("IGOR Pro", "text", null, ".ipf"),
                    new P("INI", "ini", "text/x-properties", ".ini", ".cfg", ".prefs", ".pro", ".properties"),
                    new P("IRC log", "text", "text/mirc", ".irclog", ".weechatlog"),
                    new P("Idris", "text", null, ".idr", ".lidr"),
                    new P("Inform 7", "text", null, ".ni", ".i7x"),
                    new P("Inno Setup", "text", null, ".iss"),
                    new P("Io", "io", null, ".io"),
                    new P("Ioke", "text", null, ".ik"),
                    new P("Isabelle", "text", null, ".thy"),
                    new P("J", "text", null, ".ijs"),
                    new P("JFlex", "text", null, ".flex", ".jflex"),
                    new P("JSON", "json", "application/json", ".json", ".avsc", ".geojson", ".gltf", ".JSON-tmLanguage", ".jsonl", ".tfstate", ".tfstate.backup", ".topojson", ".webapp", ".webmanifest"),
                    new P("JSON5", "javascript", "application/json", ".json5"),
                    new P("JSONLD", "javascript", null, ".jsonld"),
                    new P("JSONiq", "jsoniq", "application/json", ".jq"),
                    new P("JSX", "javascript", "text/jsx", ".jsx"),
                    new P("Jasmin", "java", null, ".j"),
                    new P("Java", "java", "text/x-java", ".java"),
                    new P("Java Server Pages", "jsp", "application/x-jsp", ".jsp"),
                    new P("JavaScript", "javascript", "text/javascript", ".js", "._js", ".bones", ".es", ".es6", ".frag", ".gs", ".jake", ".jsb", ".jscad", ".jsfl", ".jsm", ".jss", ".mjs", ".njs", ".pac", ".sjs", ".ssjs", ".xsjs", ".xsjslib"),
                    new P("Jison", "text", null, ".jison"),
                    new P("Jison Lex", "text", null, ".jisonlex"),
                    new P("Jolie", "text", null, ".ol", ".iol"),
                    new P("Julia", "julia", "text/x-julia", ".jl"),
                    new P("Jupyter Notebook", "json", "application/json", ".ipynb"),
                    new P("KRL", "text", null, ".krl"),
                    new P("KiCad Layout", "lisp", "text/x-common-lisp", ".kicad_pcb", ".kicad_mod", ".kicad_wks"),
                    new P("KiCad Legacy Layout", "text", null, ".brd"),
                    new P("KiCad Schematic", "text", null, ".sch"),
                    new P("Kit", "html", "text/html", ".kit"),
                    new P("Kotlin", "text", "text/x-kotlin", ".kt", ".ktm", ".kts"),
                    new P("LFE", "lisp", "text/x-common-lisp", ".lfe"),
                    new P("LLVM", "text", null, ".ll"),
                    new P("LOLCODE", "text", null, ".lol"),
                    new P("LSL", "lsl", null, ".lsl", ".lslp"),
                    new P("LabVIEW", "xml", "text/xml", ".lvproj"),
                    new P("Lasso", "text", null, ".lasso", ".las", ".lasso8", ".lasso9", ".ldml"),
                    new P("Latte", "smarty", "text/x-smarty", ".latte"),
                    new P("Lean", "text", null, ".lean", ".hlean"),
                    new P("Less", "less", "text/css", ".less"),
                    new P("Lex", "text", null, ".l", ".lex"),
                    new P("LilyPond", "text", null, ".ly", ".ily"),
                    new P("Limbo", "text", null, ".b", ".m"),
                    new P("Linker Script", "text", null, ".ld", ".lds", ".x"),
                    new P("Linux Kernel Module", "text", null, ".mod"),
                    new P("Liquid", "liquid", null, ".liquid"),
                    new P("Literate Agda", "text", null, ".lagda"),
                    new P("Literate CoffeeScript", "text", null, ".litcoffee"),
                    new P("Literate Haskell", "text", "text/x-literate-haskell", ".lhs"),
                    new P("LiveScript", "livescript", "text/x-livescript", ".ls", "._ls"),
                    new P("Logos", "text", null, ".xm", ".x", ".xi"),
                    new P("Logtalk", "text", null, ".lgt", ".logtalk"),
                    new P("LookML", "yaml", "text/x-yaml", ".lookml", ".model.lkml", ".view.lkml"),
                    new P("LoomScript", "text", null, ".ls"),
                    new P("Lua", "lua", "text/x-lua", ".lua", ".fcgi", ".nse", ".p8", ".pd_lua", ".rbxs", ".wlua"),
                    new P("M", "text", "text/x-mumps", ".mumps", ".m"),
                    new P("M4", "text", null, ".m4"),
                    new P("M4Sugar", "text", null, ".m4"),
                    new P("MAXScript", "text", null, ".ms", ".mcr"),
                    new P("MQL4", "c_cpp", null, ".mq4", ".mqh"),
                    new P("MQL5", "c_cpp", null, ".mq5", ".mqh"),
                    new P("MTML", "html", "text/html", ".mtml"),
                    new P("MUF", "forth", "text/x-forth", ".muf", ".m"),
                    new P("Makefile", "makefile", "text/x-cmake", ".mak", ".d", ".make", ".mk", ".mkfile"),
                    new P("Mako", "text", null, ".mako", ".mao"),
                    new P("Markdown", "markdown", "text/x-gfm", ".md", ".markdown", ".mdown", ".mdwn", ".mkd", ".mkdn", ".mkdown", ".ron", ".workbook"),
                    new P("Marko", "text", "text/html", ".marko"),
                    new P("Mask", "mask", null, ".mask"),
                    new P("Mathematica", "text", "text/x-mathematica", ".mathematica", ".cdf", ".m", ".ma", ".mt", ".nb", ".nbp", ".wl", ".wlt"),
                    new P("Matlab", "matlab", "text/x-octave", ".matlab", ".m"),
                    new P("Maven POM", "xml", "text/xml", ".pom"),
                    new P("Max", "json", "application/json", ".maxpat", ".maxhelp", ".maxproj", ".mxt", ".pat"),
                    new P("MediaWiki", "text", null, ".mediawiki", ".wiki"),
                    new P("Mercury", "prolog", null, ".m", ".moo"),
                    new P("Metal", "c_cpp", "text/x-c++src", ".metal"),
                    new P("MiniD", "text", null, ".minid"),
                    new P("Mirah", "ruby", "text/x-ruby", ".druby", ".duby", ".mir", ".mirah"),
                    new P("Modelica", "text", "text/x-modelica", ".mo"),
                    new P("Modula-2", "text", null, ".mod"),
                    new P("Module Management System", "text", null, ".mms", ".mmk"),
                    new P("Monkey", "text", null, ".monkey", ".monkey2"),
                    new P("Moocode", "text", null, ".moo"),
                    new P("MoonScript", "text", null, ".moon"),
                    new P("Myghty", "text", null, ".myt"),
                    new P("NCL", "text", null, ".ncl"),
                    new P("NL", "text", null, ".nl"),
                    new P("NSIS", "text", "text/x-nsis", ".nsi", ".nsh"),
                    new P("Nearley", "text", null, ".ne", ".nearley"),
                    new P("Nemerle", "text", null, ".n"),
                    new P("NetLinx", "text", null, ".axs", ".axi"),
                    new P("NetLinx+ERB", "text", null, ".axs.erb", ".axi.erb"),
                    new P("NetLogo", "lisp", "text/x-common-lisp", ".nlogo"),
                    new P("NewLisp", "lisp", "text/x-common-lisp", ".nl", ".lisp", ".lsp"),
                    new P("Nextflow", "groovy", null, ".nf"),
                    new P("Nginx", "text", "text/x-nginx-conf", ".nginxconf", ".vhost"),
                    new P("Nim", "text", null, ".nim", ".nimrod"),
                    new P("Ninja", "text", null, ".ninja"),
                    new P("Nit", "text", null, ".nit"),
                    new P("Nix", "nix", null, ".nix"),
                    new P("Nu", "scheme", "text/x-scheme", ".nu"),
                    new P("NumPy", "text", "text/x-python", ".numpy", ".numpyw", ".numsc"),
                    new P("OCaml", "ocaml", "text/x-ocaml", ".ml", ".eliom", ".eliomi", ".ml4", ".mli", ".mll", ".mly"),
                    new P("ObjDump", "assembly_x86", null, ".objdump"),
                    new P("Objective-C", "objectivec", "text/x-objectivec", ".m", ".h"),
                    new P("Objective-C++", "objectivec", "text/x-objectivec", ".mm"),
                    new P("Objective-J", "text", null, ".j", ".sj"),
                    new P("Omgrofl", "text", null, ".omgrofl"),
                    new P("Opa", "text", null, ".opa"),
                    new P("Opal", "text", null, ".opal"),
                    new P("OpenCL", "c_cpp", "text/x-csrc", ".cl", ".opencl"),
                    new P("OpenEdge ABL", "text", null, ".p", ".cls", ".w"),
                    new P("OpenRC runscript", "sh", "text/x-sh", null),
                    new P("OpenSCAD", "scad", null, ".scad"),
                    new P("OpenType Feature File", "text", null, ".fea"),
                    new P("Org", "text", null, ".org"),
                    new P("Ox", "text", null, ".ox", ".oxh", ".oxo"),
                    new P("Oxygene", "text", null, ".oxygene"),
                    new P("Oz", "text", "text/x-oz", ".oz"),
                    new P("P4", "text", null, ".p4"),
                    new P("PAWN", "text", null, ".pwn", ".inc"),
                    new P("PHP", "php", "application/x-httpd-php", ".php", ".aw", ".ctp", ".fcgi", ".inc", ".php3", ".php4", ".php5", ".phps", ".phpt"),
                    new P("PLSQL", "sql", "text/x-plsql", ".pls", ".bdy", ".ddl", ".fnc", ".pck", ".pkb", ".pks", ".plb", ".plsql", ".prc", ".spc", ".sql", ".tpb", ".tps", ".trg", ".vw"),
                    new P("PLpgSQL", "pgsql", "text/x-sql", ".sql"),
                    new P("POV-Ray SDL", "text", null, ".pov", ".inc"),
                    new P("Pan", "text", null, ".pan"),
                    new P("Papyrus", "text", null, ".psc"),
                    new P("Parrot", "text", null, ".parrot"),
                    new P("Parrot Assembly", "text", null, ".pasm"),
                    new P("Parrot Internal Representation", "text", null, ".pir"),
                    new P("Pascal", "pascal", "text/x-pascal", ".pas", ".dfm", ".dpr", ".inc", ".lpr", ".pascal", ".pp"),
                    new P("Pep8", "text", null, ".pep"),
                    new P("Perl", "perl", "text/x-perl", ".pl", ".al", ".cgi", ".fcgi", ".perl", ".ph", ".plx", ".pm", ".psgi", ".t"),
                    new P("Perl 6", "perl", "text/x-perl", ".6pl", ".6pm", ".nqp", ".p6", ".p6l", ".p6m", ".pl", ".pl6", ".pm", ".pm6", ".t"),
                    new P("Pic", "text", "text/troff", ".pic", ".chem"),
                    new P("Pickle", "text", null, ".pkl"),
                    new P("PicoLisp", "lisp", null, ".l"),
                    new P("PigLatin", "text", null, ".pig"),
                    new P("Pike", "text", null, ".pike", ".pmod"),
                    new P("Pod", "perl", "text/x-perl", ".pod"),
                    new P("PogoScript", "text", null, ".pogo"),
                    new P("Pony", "text", null, ".pony"),
                    new P("PostCSS", "text", null, ".pcss"),
                    new P("PostScript", "text", null, ".ps", ".eps", ".pfa"),
                    new P("PowerBuilder", "text", null, ".pbt", ".sra", ".sru", ".srw"),
                    new P("PowerShell", "powershell", "application/x-powershell", ".ps1", ".psd1", ".psm1"),
                    new P("Processing", "text", null, ".pde"),
                    new P("Prolog", "prolog", null, ".pl", ".pro", ".prolog", ".yap"),
                    new P("Propeller Spin", "text", null, ".spin"),
                    new P("Protocol Buffer", "protobuf", "text/x-protobuf", ".proto"),
                    new P("Public Key", "text", "application/pgp", ".asc", ".pub"),
                    new P("Pug", "jade", "text/x-pug", ".jade", ".pug"),
                    new P("Puppet", "text", "text/x-puppet", ".pp"),
                    new P("Pure Data", "text", null, ".pd"),
                    new P("PureBasic", "text", null, ".pb", ".pbi"),
                    new P("PureScript", "haskell", "text/x-haskell", ".purs"),
                    new P("Python", "python", "text/x-python", ".py", ".bzl", ".cgi", ".fcgi", ".gyp", ".gypi", ".lmi", ".py3", ".pyde", ".pyi", ".pyp", ".pyt", ".pyw", ".rpy", ".spec", ".tac", ".wsgi", ".xpy"),
                    new P("Python traceback", "text", null, ".pytb"),
                    new P("QML", "text", null, ".qml", ".qbs"),
                    new P("QMake", "text", null, ".pro", ".pri"),
                    new P("R", "r", "text/x-rsrc", ".r", ".rd", ".rsx"),
                    new P("RAML", "yaml", "text/x-yaml", ".raml"),
                    new P("RDoc", "rdoc", null, ".rdoc"),
                    new P("REALbasic", "text", null, ".rbbas", ".rbfrm", ".rbmnu", ".rbres", ".rbtbar", ".rbuistate"),
                    new P("REXX", "text", null, ".rexx", ".pprx", ".rex"),
                    new P("RHTML", "rhtml", "application/x-erb", ".rhtml"),
                    new P("RMarkdown", "markdown", "text/x-gfm", ".rmd"),
                    new P("RPC", "c_cpp", null, ".x"),
                    new P("RPM Spec", "text", "text/x-rpm-spec", ".spec"),
                    new P("RUNOFF", "text", null, ".rnh", ".rno"),
                    new P("Racket", "lisp", null, ".rkt", ".rktd", ".rktl", ".scrbl"),
                    new P("Ragel", "text", null, ".rl"),
                    new P("Rascal", "text", null, ".rsc"),
                    new P("Raw token data", "text", null, ".raw"),
                    new P("Reason", "rust", "text/x-rustsrc", ".re", ".rei"),
                    new P("Rebol", "text", null, ".reb", ".r", ".r2", ".r3", ".rebol"),
                    new P("Red", "text", null, ".red", ".reds"),
                    new P("Redcode", "text", null, ".cw"),
                    new P("Regular Expression", "text", null, ".regexp", ".regex"),
                    new P("Ren'Py", "python", null, ".rpy"),
                    new P("RenderScript", "text", null, ".rs", ".rsh"),
                    new P("Ring", "text", null, ".ring"),
                    new P("RobotFramework", "text", null, ".robot"),
                    new P("Roff", "text", "text/troff", ".man", ".1", ".1in", ".1m", ".1x", ".2", ".3", ".3in", ".3m", ".3qt", ".3x", ".4", ".5", ".6", ".7", ".8", ".9", ".l", ".me", ".ms", ".n", ".nr", ".rno", ".roff", ".tmac"),
                    new P("Rouge", "clojure", "text/x-clojure", ".rg"),
                    new P("Ruby", "ruby", "text/x-ruby", ".rb", ".builder", ".eye", ".fcgi", ".gemspec", ".god", ".jbuilder", ".mspec", ".pluginspec", ".podspec", ".rabl", ".rake", ".rbuild", ".rbw", ".rbx", ".ru", ".ruby", ".spec", ".thor", ".watchr"),
                    new P("Rust", "rust", "text/x-rustsrc", ".rs", ".rs.in"),
                    new P("SAS", "text", "text/x-sas", ".sas"),
                    new P("SCSS", "scss", "text/x-scss", ".scss"),
                    new P("SMT", "text", null, ".smt2", ".smt"),
                    new P("SPARQL", "text", "application/sparql-query", ".sparql", ".rq"),
                    new P("SQF", "text", null, ".sqf", ".hqf"),
                    new P("SQL", "sql", "text/x-sql", ".sql", ".cql", ".ddl", ".inc", ".mysql", ".prc", ".tab", ".udf", ".viw"),
                    new P("SQLPL", "sql", "text/x-sql", ".sql", ".db2"),
                    new P("SRecode Template", "lisp", "text/x-common-lisp", ".srt"),
                    new P("STON", "text", null, ".ston"),
                    new P("SVG", "xml", "text/xml", ".svg"),
                    new P("Sage", "python", "text/x-python", ".sage", ".sagews"),
                    new P("SaltStack", "yaml", "text/x-yaml", ".sls"),
                    new P("Sass", "sass", "text/x-sass", ".sass"),
                    new P("Scala", "scala", "text/x-scala", ".scala", ".kojo", ".sbt", ".sc"),
                    new P("Scaml", "text", null, ".scaml"),
                    new P("Scheme", "scheme", "text/x-scheme", ".scm", ".sch", ".sld", ".sls", ".sps", ".ss"),
                    new P("Scilab", "text", null, ".sci", ".sce", ".tst"),
                    new P("Self", "text", null, ".self"),
                    new P("ShaderLab", "text", null, ".shader"),
                    new P("Shell", "sh", "text/x-sh", ".sh", ".bash", ".bats", ".cgi", ".command", ".fcgi", ".ksh", ".sh.in", ".tmux", ".tool", ".zsh"),
                    new P("ShellSession", "sh", "text/x-sh", ".sh-session"),
                    new P("Shen", "text", null, ".shen"),
                    new P("Slash", "text", null, ".sl"),
                    new P("Slim", "text", "text/x-slim", ".slim"),
                    new P("Smali", "text", null, ".smali"),
                    new P("Smalltalk", "text", "text/x-stsrc", ".st", ".cs"),
                    new P("Smarty", "smarty", "text/x-smarty", ".tpl"),
                    new P("SourcePawn", "text", null, ".sp", ".inc", ".sma"),
                    new P("Spline Font Database", "yaml", null, ".sfd"),
                    new P("Squirrel", "c_cpp", "text/x-c++src", ".nut"),
                    new P("Stan", "text", null, ".stan"),
                    new P("Standard ML", "text", "text/x-ocaml", ".ML", ".fun", ".sig", ".sml"),
                    new P("Stata", "text", null, ".do", ".ado", ".doh", ".ihlp", ".mata", ".matah", ".sthlp"),
                    new P("Stylus", "stylus", null, ".styl"),
                    new P("SubRip Text", "text", null, ".srt"),
                    new P("Sublime Text Config", "javascript", "text/javascript", ".sublime-build", ".sublime-commands", ".sublime-completions", ".sublime-keymap", ".sublime-macro", ".sublime-menu", ".sublime-mousemap", ".sublime-project", ".sublime-settings", ".sublime-theme", ".sublime-workspace", ".sublime_metrics", ".sublime_session"),
                    new P("SugarSS", "text", null, ".sss"),
                    new P("SuperCollider", "text", null, ".sc", ".scd"),
                    new P("Swift", "text", "text/x-swift", ".swift"),
                    new P("SystemVerilog", "verilog", "text/x-systemverilog", ".sv", ".svh", ".vh"),
                    new P("TI Program", "text", null, ".8xp", ".8xk", ".8xk.txt", ".8xp.txt"),
                    new P("TLA", "text", null, ".tla"),
                    new P("TOML", "toml", "text/x-toml", ".toml"),
                    new P("TXL", "text", null, ".txl"),
                    new P("Tcl", "tcl", "text/x-tcl", ".tcl", ".adp", ".tm"),
                    new P("Tcsh", "sh", "text/x-sh", ".tcsh", ".csh"),
                    new P("TeX", "tex", "text/x-stex", ".tex", ".aux", ".bbx", ".bib", ".cbx", ".cls", ".dtx", ".ins", ".lbx", ".ltx", ".mkii", ".mkiv", ".mkvi", ".sty", ".toc"),
                    new P("Tea", "text", null, ".tea"),
                    new P("Terra", "lua", "text/x-lua", ".t"),
                    new P("Text", "text", null, ".txt", ".fr", ".nb", ".ncl", ".no"),
                    new P("Textile", "textile", "text/x-textile", ".textile"),
                    new P("Thrift", "text", null, ".thrift"),
                    new P("Turing", "text", null, ".t", ".tu"),
                    new P("Turtle", "text", "text/turtle", ".ttl"),
                    new P("Twig", "twig", "text/x-twig", ".twig"),
                    new P("Type Language", "text", null, ".tl"),
                    new P("TypeScript", "typescript", "application/typescript", ".ts", ".tsx"),
                    new P("Unified Parallel C", "c_cpp", "text/x-csrc", ".upc"),
                    new P("Unity3D Asset", "yaml", "text/x-yaml", ".anim", ".asset", ".mat", ".meta", ".prefab", ".unity"),
                    new P("Unix Assembly", "assembly_x86", null, ".s", ".ms"),
                    new P("Uno", "csharp", "text/x-csharp", ".uno"),
                    new P("UnrealScript", "java", "text/x-java", ".uc"),
                    new P("UrWeb", "text", null, ".ur", ".urs"),
                    new P("VCL", "text", null, ".vcl"),
                    new P("VHDL", "vhdl", "text/x-vhdl", ".vhdl", ".vhd", ".vhf", ".vhi", ".vho", ".vhs", ".vht", ".vhw"),
                    new P("Vala", "vala", null, ".vala", ".vapi"),
                    new P("Verilog", "verilog", "text/x-verilog", ".v", ".veo"),
                    new P("Vim script", "text", null, ".vim"),
                    new P("Visual Basic", "text", "text/x-vb", ".vb", ".bas", ".cls", ".frm", ".frx", ".vba", ".vbhtml", ".vbs"),
                    new P("Volt", "d", "text/x-d", ".volt"),
                    new P("Vue", "html", null, ".vue"),
                    new P("Wavefront Material", "text", null, ".mtl"),
                    new P("Wavefront Object", "text", null, ".obj"),
                    new P("Web Ontology Language", "xml", null, ".owl"),
                    new P("WebAssembly", "lisp", "text/x-common-lisp", ".wast", ".wat"),
                    new P("WebIDL", "text", "text/x-webidl", ".webidl"),
                    new P("World of Warcraft Addon Data", "text", null, ".toc"),
                    new P("X10", "text", null, ".x10"),
                    new P("XC", "c_cpp", "text/x-csrc", ".xc"),
                    new P("XML", "xml", "text/xml", ".xml", ".adml", ".admx", ".ant", ".axml", ".builds", ".ccproj", ".ccxml", ".clixml", ".cproject", ".cscfg", ".csdef", ".csl", ".csproj", ".ct", ".depproj", ".dita", ".ditamap", ".ditaval", ".dll.config", ".dotsettings", ".filters", ".fsproj", ".fxml", ".glade", ".gml", ".grxml", ".iml", ".ivy", ".jelly", ".jsproj", ".kml", ".launch", ".mdpolicy", ".mjml", ".mm", ".mod", ".mxml", ".natvis", ".ndproj", ".nproj", ".nuspec", ".odd", ".osm", ".pkgproj", ".plist", ".pluginspec", ".proj", ".props", ".ps1xml", ".psc1", ".pt", ".rdf", ".resx", ".rss", ".sch", ".scxml", ".sfproj", ".shproj", ".srdf", ".storyboard", ".stTheme", ".sublime-snippet", ".targets", ".tmCommand", ".tml", ".tmLanguage", ".tmPreferences", ".tmSnippet", ".tmTheme", ".ts", ".tsx", ".ui", ".urdf", ".ux", ".vbproj", ".vcxproj", ".vsixmanifest", ".vssettings", ".vstemplate", ".vxml", ".wixproj", ".wsdl", ".wsf", ".wxi", ".wxl", ".wxs", ".x3d", ".xacro", ".xaml", ".xib", ".xlf", ".xliff", ".xmi", ".xml.dist", ".xproj", ".xsd", ".xspec", ".xul", ".zcml"),
                    new P("XPM", "c_cpp", null, ".xpm", ".pm"),
                    new P("XPages", "xml", "text/xml", ".xsp-config", ".xsp.metadata"),
                    new P("XProc", "xml", "text/xml", ".xpl", ".xproc"),
                    new P("XQuery", "xquery", "application/xquery", ".xquery", ".xq", ".xql", ".xqm", ".xqy"),
                    new P("XS", "c_cpp", "text/x-csrc", ".xs"),
                    new P("XSLT", "xml", "text/xml", ".xslt", ".xsl"),
                    new P("Xojo", "text", null, ".xojo_code", ".xojo_menu", ".xojo_report", ".xojo_script", ".xojo_toolbar", ".xojo_window"),
                    new P("Xtend", "text", null, ".xtend"),
                    new P("YAML", "yaml", "text/x-yaml", ".yml", ".reek", ".rviz", ".sublime-syntax", ".syntax", ".yaml", ".yaml-tmlanguage", ".yml.mysql"),
                    new P("YANG", "text", null, ".yang"),
                    new P("YARA", "text", null, ".yar", ".yara"),
                    new P("Yacc", "text", null, ".y", ".yacc", ".yy"),
                    new P("Zephir", "php", null, ".zep"),
                    new P("Zimpl", "text", null, ".zimpl", ".zmpl", ".zpl"),
                    new P("desktop", "text", null, ".desktop", ".desktop.in"),
                    new P("eC", "text", null, ".ec", ".eh"),
                    new P("edn", "clojure", "text/x-clojure", ".edn"),
                    new P("fish", "text", null, ".fish"),
                    new P("mupad", "text", null, ".mu"),
                    new P("nesC", "text", null, ".nc"),
                    new P("ooc", "text", null, ".ooc"),
                    new P("reStructuredText", "text", "text/x-rst", ".rst", ".rest", ".rest.txt", ".rst.txt"),
                    new P("wdl", "text", null, ".wdl"),
                    new P("wisp", "clojure", "text/x-clojure", ".wisp"),
                    new P("xBase", "text", null, ".prg", ".ch", ".prw")
            );
        }
    }
}
